 SELECT 
                    [TBLOCACAO].ID AS ID,
                    [TBCLIENTEPJ].NOME AS NOMECLIENTE,
                    [TBCLIENTEPJ].ID AS IDCLIENTE,
                    [TBCLIENTEPJ].ENDERECO AS ENDERECOCLIENTE,
                    [TBCLIENTEPJ].EMAIL AS EMAILCLIENTE,
                    [TBCLIENTEPJ].CIDADE AS CIDADECLIENTE,
                    [TBCLIENTEPJ].ESTADO AS ESTADOCLIENTE,
                    [TBCLIENTEPJ].TELEFONE AS TELEFONECLIENTE,
                    [TBCLIENTEPJ].CELULAR AS CELULARCLIENTE,
                    [TBCLIENTEPJ].CNPJ AS CNPJ,


                    TBCONDUTOR.NOMECONDUTOR AS NOMECONDUTOR,
                    [TBLOCACAO].IDCONDUTOR AS IDCONDUTOR,
                    TBCONDUTOR.ENDERECO AS ENDERECOCONDUTOR,
                    TBCONDUTOR.EMAIL AS EMAILCONDUTOR,
                    TBCONDUTOR.CIDADE AS CIDADECONDUTOR,
                    TBCONDUTOR.ESTADO AS ESTADOCONFUTOR,
                    TBCONDUTOR.TELEFONE AS TELEFONECONDUTOR,
                    TBCONDUTOR.CELULAR AS CELULARCONDUTOR,
                    TBCONDUTOR.RG AS RGCONDUTOR,
                    TBCONDUTOR.CPF AS CPFCONDUTOR,
                    TBCONDUTOR.CNH AS CNHCONDUTOR,
                    TBCONDUTOR.VALIDADECNH AS VALIDADECNHCONDUTOR,
                    TBCONDUTOR.IDCLIENTECNPJ AS IDCLIENTECNPJ,

                    [TBVEICULOS].VEICULO AS VEICULO, 
                    [TBVEICULOS].ID AS IDVEICULO,
                    [TBVEICULOS].COR AS CORVEICULO,
                    [TBVEICULOS].KMATUAL AS KMATUALVEICULO,
                    [TBVEICULOS].PORTAMALAS AS PORTAMALASVEICULO,
                    [TBVEICULOS].NUMEROPORTAS AS NUMEROPORTASVEICULO,
                    [TBVEICULOS].ANO AS ANOVEICULO,
                    [TBVEICULOS].CHASSI AS CHASSIVEICULO,
                    [TBVEICULOS].MARCA AS MARCAVEICULO,
                    [TBVEICULOS].LITROSTANQUE AS TANQUEVEICULO,
                    [TBVEICULOS].PLACA AS PLACAVEICULO,
                    [TBVEICULOS].CAPACIDADE AS CAPACIDADEVEICULO,
                    [TBVEICULOS].GRUPO AS GRUPOVEICULO,
                    [TBVEICULOS].IMAGEM AS IMAGEMVEICULO,

                    [TBGRUPODEVEICULOS].NOME AS NOMEGRUPOVEICULO,
                    [TBGRUPODEVEICULOS].VALORDIARIA AS VALORDIARIA,
                    [TBGRUPODEVEICULOS].VALORKMCONTROLADO AS VALORKMCONTROLADO,
                    [TBGRUPODEVEICULOS].VALORKMDIARIA AS VALORKMDIARIA,
                    [TBGRUPODEVEICULOS].VALORKMLIVRE AS VALORKMLIVRE,
                    [TBGRUPODEVEICULOS].LIMITEKMCONTROLADO AS LIMITEKMCONTROLADO,


                    [TBTAXASESERVICOS].NOME AS TAXASESERVICOS,  
                    [TBTAXASESERVICOS].ID AS IDTAXASESERVICOS,
                    [TBTAXASESERVICOS].VALOR AS VALORTAXASESERVICOS,
                    [TBTAXASESERVICOS].CALCULODIARIO AS CALCULODIARIOTAXASESERVICOS,
                    [TBTAXASESERVICOS].CALCULOFIXO AS CALCULOFIXOTAXASESERVICOS,

 
                    [PLANO],
                    [VALORTOTAL],
                    [VALORCAUCAO],
                    [DATASAIDA],
                    [DATARETORNO],
                    [KMINICIAL],
                    [KMFINAL]

            FROM
                    [TBLOCACAO]  INNER JOIN [TBVEICULOS]
            ON      [TBLOCACAO].IDVEICULO = [TBVEICULOS].ID
                    
                    INNER JOIN  [TBGRUPODEVEICULOS]
            ON      [TBVEICULOS].GRUPO = [TBGRUPODEVEICULOS].ID
             
                    INNER JOIN  [TBCONDUTOR]
            ON      [TBLOCACAO].IDCONDUTOR = [TBCONDUTOR].ID

                    INNER JOIN  [TBCLIENTEPJ]
            ON      [TBLOCACAO].IDCLIENTEPJ = [TBCLIENTEPJ].ID

                    INNER JOIN  [TBTAXASESERVICOS]
             ON     [TBLOCACAO].IDTAXASESERVICOS = [TBTAXASESERVICOS].ID

             WHERE [TBLOCACAO].Id = @ID;